In [1]:
import sqlite3
import pandas as pd

conn=sqlite3.connect("../data/analytics.db")

In [3]:
tables=pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print(tables)

                name
0           products
1       transactions
2  transaction_items

In [4]:
for t in tables['name']:
    count=pd.read_sql(f"SELECT COUNT(*) as rows FROM {t};", conn)
    print(f"Table: {t}, Count: {count.iloc[0]['rows']}")

Table: products, Count: 500
Table: transactions, Count: 20000
Table: transaction_items, Count: 68249

In [5]:
pd.read_sql("SELECT * FROM products LIMIT 5;", conn)

,product_id,barcode,name,brand,category,pack_size,base_price,cost
0,1,100000000001,Product 1,Brand 32,Frozen,1000g,24.09,2.82
1,2,100000000002,Product 2,Brand 5,Produce,1000g,18.22,12.58
2,3,100000000003,Product 3,Brand 36,Produce,200g,3.66,4.93
3,4,100000000004,Product 4,Brand 17,Frozen,1000g,4.64,10.03
4,5,100000000005,Product 5,Brand 2,Beverages,200g,24.40,9.64

In [6]:
pd.read_sql("SELECT * FROM transaction_items LIMIT 5;", conn)

   transaction_id  product_id  quantity  price
0               1         102         1   2.56
1               1         378         1  16.87
2               1         148         3   7.83
3               1         472         1   8.66
4               1         441         1   2.61

In [7]:
pd.read_sql("SELECT * FROM products p join transaction_items ti on p.product_id=ti.product_id LIMIT 5;", conn)

,product_id,barcode,name,brand,category,pack_size,base_price,cost,transaction_id,product_id,quantity,price
0,1,100000000001,Product 1,Brand 32,Frozen,1000g,24.09,2.82,156,1,1,24.09
1,1,100000000001,Product 1,Brand 32,Frozen,1000g,24.09,2.82,698,1,1,24.09
2,1,100000000001,Product 1,Brand 32,Frozen,1000g,24.09,2.82,806,1,1,24.09
3,1,100000000001,Product 1,Brand 32,Frozen,1000g,24.09,2.82,912,1,1,24.09
4,1,100000000001,Product 1,Brand 32,Frozen,1000g,24.09,2.82,1171,1,1,24.09

In [ ]:
# Sum of prices in transaction_items
pd.read_sql("SELECT sum(price) FROM transaction_items group by transaction_id;", conn)

       sum(price)
0           51.81
1           66.00
2           29.90
3           43.30
4           51.85
...           ...
19995       53.30
19996        9.50
19997       49.97
19998       26.96
19999       56.00

[20000 rows x 1 columns]

In [20]:
# Max of prices in transaction_items
pd.read_sql("SELECT *,max(prices) FROM (SELECT *,sum(price) as prices FROM transaction_items group by transaction_id) as subquery;", conn)

   transaction_id  product_id  quantity  price  prices  max(prices)
0            8804          53         3  23.28  132.59       132.59